name: Reusable Build

on:
  workflow_call:
    secrets:
      USE_LOCKFILE:
        required: true
      ENABLE_RELEASE:
        required: true
      NPM_TOKEN:
        required: true

jobs:
  build:
    if: "! contains(toJSON(github.event.commits.*.message), '[skip ci]') && ! contains(toJSON(github.event.commits.*.message), '(no-release)')"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ["lts/*"]

    steps:
    - uses: actions/checkout@v4

    - uses: ./.github/actions/composite-setup
      with:
        USE_LOCKFILE: ${{ secrets.USE_LOCKFILE }}

    - run: pnpm build

    - run: pnpm lint

    - run: pnpm test
    
    - name: Coverage
      if: ${{ github.event_name == 'pull_request' }}
      uses: romeovs/lcov-reporter-action@v0.3.1
